### ISSUE TITLE
Blog reply problem

### ISSUE THREAD

**Issue by rodrigosiviero** [RafPe/hubot-zabbix-scripts#3]
Hi RafPe,

First of all I'm sorry to open this issue here, this was the only way to contact you, I'm trying to leave a reply on your post:  https://rafpe.ninja/2017/02/11/gitlab-custom-pre-receive-hook/  but i'ts throwing me phpmailer error.

So let me reply here:

> 
> Hi,
> Great post, I'm trying to achieve the exactly same thing, this is a good approach but how can I hide the secret code from the commit msg if every developer has access to it?

If you can help us out would be awesome, my email is rodrigosiviero at gmail

**Comment by RafPe** [comment]
Hi @rodrigosiviero ,

I bet the simplest will do the work :D 

```
#!/usr/bin/env ruby
require 'digest/sha1'


t = Time.now
our_secret = Digest::SHA1.hexdigest("super-duper-sercret-#{t.hour.to_i}-#{t.min.to_i}")
```

And then only you know what commit message needs to be. Of course further customisations are possible. 

BTW comments are working - just approve is not automatic :) 

Good luck! 

Regards
Rafal
