### ISSUE TITLE
can't find '__main__' module error

### ISSUE THREAD

**Issue by lalkrishnak** [RafPe/hubot-zabbix-scripts#5]
Hi RafPe,

I have followed every steps which you have mentioned in Readme.MD. But I'm getting below error while executing "zbx-maint set 172.17.0.208 1 test" in Slack.

Error Details

/usr/bin/python: can't find '__main__' module in '/home/xyz/hubot/node_modules/hubot-zabbix-maintanance/src'

The script works fine when I execute it manually like below.

./zbx-maint.py -u admin -p zabbix -s http://172.17.0.200/zabbix -a del -i zabbixbot:983c8697-228e-4373-930c-e51313a78d91

Could you please suggest me what needs to be done.

Thanks,
Lal

**Comment by RafPe** [comment]
Can you uninstall the node modules for Hubot ? Uploaded previous readme file

**Comment by lalkrishnak** [comment]
Thank you for the new README file.

I have done a fresh installation and still getting **"/usr/bin/python: can't find '__main__' module in '/home/xyz/hubot/scripts'**  error while executing **zbx-maint set 172.17.0.208 1 test** .

**Comment by lalkrishnak** [comment]
xyz@c02807bc2133:~/hubot$ echo $HUBOT_ZBX_USER
admin
xyz@c02807bc2133:~/hubot$ echo $HUBOT_ZBX_PW
zabbix
xyz@c02807bc2133:~/hubot$ echo $HUBOT_ZBX_URL
http://172.17.0.200/zabbix
xyz@c02807bc2133:~/hubot$ echo $HUBOT_ZBX_PYMAINT
/home/xyz/hubot/scripts/zbx-maint.py


xyz@c02807bc2133:~/hubot/scripts$ python zbx-maint.py -u admin -p zabbix -s http://172.17.0.200/zabbix -t 172.17.0.208 -a set -l 10 -d Test
Helping out *@None* to be quiet as ninja when working :)
query               = '172.17.0.208'
state               = set
minutes             = 10
name/id             = bender:1a081e92-8355-4157-8586-7077d46364f9
desc                = Test
collect_data        = 1
timeout             = 5
requestor           = None
Found 0 group(s) / 1 host(s)
Success! Created maintanance for 0 groups/1 hosts with name *bender:1a081e92-8355-4157-8586-7077d46364f9*
Reference IDs: *6*
So now :) go and have fun!

xyz@c02807bc2133:~/hubot$ python
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2

**Comment by lalkrishnak** [comment]
**Debug mode entries below.**

[Wed Aug 30 2017 14:47:29 GMT+0000 (UTC)] DEBUG Received message: 'zbx-maint set 172.17.0.208 1 test' in channel: lalkrishna, from: lalkrishna
[Wed Aug 30 2017 14:47:29 GMT+0000 (UTC)] DEBUG Message 'zabbixbot zbx-maint set 172.17.0.208 1 test' matched regex //^\s*[@]?zabbixbot[:,]?\s*(?:zbx-maint\s(set)\s(["]?\w.*)\s(\d+)\s(["]?\w.*))/i/; listener.options = { id: null }
[Wed Aug 30 2017 14:47:29 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'zabbixbot zbx-maint set 172.17.0.208 1 test'
[Wed Aug 30 2017 14:47:29 GMT+0000 (UTC)] DEBUG Sending to lalkrishna: /usr/bin/python: can't find '__main__' module in '/home/xyz/hubot/scripts'

**Comment by RafPe** [comment]
@lalkrishnak  try pulling from https://github.com/RafPe/hubot-zabbix-scripts/tree/fix_patg and let me know if that one helps

**Comment by lalkrishnak** [comment]
@RafPe 
Thanks a ton. It worked!
You really saved my day.
